-- Additive migration. Run once through the authorized Supabase SQL editor.
-- Public signup does NOT grant workspace access: membership must be added by an administrator.
create table if not exists public.hyopu_members (
  user_id uuid primary key references auth.users(id) on delete cascade,
  pic text check (pic in ('DENNIS','JAE LEE','JACK','RICK')),
  role text not null default 'editor' check (role in ('editor','viewer')),
  created_at timestamptz not null default now()
);
create table if not exists public.hyopu_port_calls (
  id text primary key,
  data jsonb not null check (jsonb_typeof(data) = 'object'),
  revision integer not null default 1 check (revision > 0),
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);
alter table public.hyopu_members enable row level security;
alter table public.hyopu_port_calls enable row level security;
revoke all on public.hyopu_members, public.hyopu_port_calls from anon, authenticated;
grant all on public.hyopu_members, public.hyopu_port_calls to service_role;
-- No browser/anonymous policies. API verifies Auth user + membership before every read/write.
-- Conditional PATCH by primary key AND revision prevents silent concurrent overwrite.
insert into public.hyopu_port_calls (id,data,revision) values
('eta-2026-001', '{"vessel":"S.PONDO","voyage":"PACS 116 + HBR 117","port":"ULSAN","etaRaw":"08/21 0618","remark":"INPORT","etdRaw":"09/03 1600","pic":"DENNIS","highlight":[],"id":"eta-2026-001","year":2026,"status":"INPORT","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-002', '{"vessel":"S.PERSEVERANCE","voyage":"HBR 131","port":"ULSAN","etaRaw":"08/26 1100","remark":"INPORT","etdRaw":"09/06 1400","pic":"JAE LEE","highlight":[],"id":"eta-2026-002","year":2026,"status":"INPORT","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-003', '{"vessel":"S.VOYAGER","voyage":"488","port":"P''TAEK","etaRaw":"09/02 1636","remark":"INPORT","etdRaw":"09/09 0500","pic":"JACK","highlight":[],"id":"eta-2026-003","year":2026,"status":"INPORT","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-004', '{"vessel":"S.PRIDE","voyage":"HBR 53","port":"ULSAN","etaRaw":"09/03 0800","remark":"","etdRaw":"","pic":"RICK","highlight":[],"id":"eta-2026-004","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-005', '{"vessel":"S.RENGE","voyage":"92","port":"ULSAN","etaRaw":"09/04 1700","remark":"","etdRaw":"","pic":"JAE LEE","highlight":[],"id":"eta-2026-005","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-006', '{"vessel":"S.PONDO","voyage":"HBR 117","port":"YOSU","etaRaw":"09/04 0800","remark":"","etdRaw":"","pic":"DENNIS","highlight":[],"id":"eta-2026-006","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-007', '{"vessel":"S.AJISAI","voyage":"134","port":"ULSAN","etaRaw":"09/04 2000","remark":"","etdRaw":"","pic":"JACK","highlight":[],"id":"eta-2026-007","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-008', '{"vessel":"S.CONFIDENCE","voyage":"TPW 196","port":"ULSAN","etaRaw":"09/05 2300","remark":"","etdRaw":"","pic":"JAE LEE","highlight":[],"id":"eta-2026-008","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-009', '{"vessel":"S.RENGE","voyage":"92","port":"DAESAN","etaRaw":"09/05 1200??","remark":"","etdRaw":"","pic":"JAE LEE","highlight":[],"id":"eta-2026-009","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-010', '{"vessel":"S.VOYAGER","voyage":"488","port":"ULSAN","etaRaw":"09/05 1500","remark":"","etdRaw":"","pic":"JACK","highlight":[],"id":"eta-2026-010","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-011', '{"vessel":"S.PONDO","voyage":"HBR 117","port":"P''TAEK","etaRaw":"09/05","remark":"","etdRaw":"","pic":"DENNIS","highlight":[],"id":"eta-2026-011","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-012', '{"vessel":"S.DISTRIBUTOR","voyage":"584","port":"P''TAEK","etaRaw":"09/06??","remark":"","etdRaw":"","pic":"JACK","highlight":[],"id":"eta-2026-012","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-013', '{"vessel":"S.RENGE","voyage":"92","port":"P''TAEK","etaRaw":"09/06 2000","remark":"","etdRaw":"","pic":"JAE LEE","highlight":[],"id":"eta-2026-013","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-014', '{"vessel":"S.CALLUNA","voyage":"BAJ 62(OPA)","port":"ULSAN","etaRaw":"09/08 2200","remark":"","etdRaw":"","pic":"DENNIS","highlight":[],"id":"eta-2026-014","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-015', '{"vessel":"ZI LUO LAN","voyage":"V2625","port":"ULSAN","etaRaw":"09/09","remark":"","etdRaw":"","pic":"JACK","highlight":["vessel"],"id":"eta-2026-015","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-016', '{"vessel":"S.LARIX","voyage":"PACS 75","port":"ULSAN","etaRaw":"09/09 PM","remark":"","etdRaw":"","pic":"DENNIS","highlight":[],"id":"eta-2026-016","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-017', '{"vessel":"S.DISTRIBUTOR","voyage":"585+586","port":"ULSAN","etaRaw":"09/12","remark":"","etdRaw":"","pic":"JACK","highlight":[],"id":"eta-2026-017","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-018', '{"vessel":"S.TSUBAKI","voyage":"134","port":"ULSAN","etaRaw":"09/11","remark":"","etdRaw":"","pic":"JAE LEE","highlight":[],"id":"eta-2026-018","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-019', '{"vessel":"S.ENDURANCE","voyage":"TRAMP 150(OPA)","port":"YOSU","etaRaw":"09/12 AM","remark":"","etdRaw":"","pic":"RICK","highlight":["port"],"id":"eta-2026-019","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-020', '{"vessel":"S.VOYAGER","voyage":"489","port":"ULSAN","etaRaw":"09/14","remark":"","etdRaw":"","pic":"JACK","highlight":[],"id":"eta-2026-020","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-021', '{"vessel":"S.FOCUS","voyage":"TPW 94","port":"ULSAN","etaRaw":"09/15 1700","remark":"","etdRaw":"","pic":"JAE LEE","highlight":[],"id":"eta-2026-021","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-022', '{"vessel":"S.VIRTUE","voyage":"PACS 139+HBR140","port":"ULSAN","etaRaw":"09/17 PM","remark":"","etdRaw":"","pic":"DENNIS","highlight":[],"id":"eta-2026-022","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-023', '{"vessel":"S.SINCERITY","voyage":"HBR 62","port":"DAESAN","etaRaw":"09/22","remark":"","etdRaw":"","pic":"RICK","highlight":[],"id":"eta-2026-023","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-024', '{"vessel":"S.RINDO","voyage":"222","port":"DAESAN","etaRaw":"09/23","remark":"","etdRaw":"","pic":"JACK","highlight":[],"id":"eta-2026-024","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-025', '{"vessel":"S.CALLUNA","voyage":"HBR 63","port":"ULSAN","etaRaw":"09/24","remark":"","etdRaw":"","pic":"DENNIS","highlight":[],"id":"eta-2026-025","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-026', '{"vessel":"S.SINCERITY","voyage":"HBR 62","port":"ULSAN","etaRaw":"09/25","remark":"","etdRaw":"","pic":"RICK","highlight":[],"id":"eta-2026-026","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-027', '{"vessel":"S.RINDO","voyage":"222","port":"ULSAN","etaRaw":"09/26","remark":"","etdRaw":"","pic":"JACK","highlight":[],"id":"eta-2026-027","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-028', '{"vessel":"S.DISTRIBUTOR","voyage":"586","port":"P''TAEK","etaRaw":"09/28","remark":"","etdRaw":"","pic":"JACK","highlight":[],"id":"eta-2026-028","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-029', '{"vessel":"S.RINDO","voyage":"222","port":"DONGHAE","etaRaw":"09/30","remark":"","etdRaw":"","pic":"JACK","highlight":[],"id":"eta-2026-029","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-030', '{"vessel":"S.DISTRIBUTOR","voyage":"586","port":"DAESAN","etaRaw":"09/30","remark":"","etdRaw":"","pic":"JACK","highlight":[],"id":"eta-2026-030","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-031', '{"vessel":"SUN MERCURY","voyage":"27","port":"P''TAEK","etaRaw":"09/30","remark":"","etdRaw":"","pic":"JAE LEE","highlight":[],"id":"eta-2026-031","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-032', '{"vessel":"SUN MERCURY","voyage":"27","port":"ULSAN","etaRaw":"10/03","remark":"","etdRaw":"","pic":"JAE LEE","highlight":[],"id":"eta-2026-032","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-033', '{"vessel":"S.APAL","voyage":"TPW 64","port":"ULSAN","etaRaw":"10/04 1700","remark":"","etdRaw":"","pic":"RICK","highlight":[],"id":"eta-2026-033","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-034', '{"vessel":"SUN GAIA","voyage":"3","port":"DAESAN","etaRaw":"10/05","remark":"","etdRaw":"","pic":"JAE LEE","highlight":[],"id":"eta-2026-034","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-035', '{"vessel":"S.INTEGRITY","voyage":"TPW 46","port":"ULSAN","etaRaw":"10/10 2200","remark":"","etdRaw":"","pic":"DENNIS","highlight":[],"id":"eta-2026-035","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-036', '{"vessel":"KISO","voyage":"TPW 3","port":"ULSAN","etaRaw":"10/11","remark":"","etdRaw":"","pic":"JAE LEE","highlight":[],"id":"eta-2026-036","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-037', '{"vessel":"GOLDEN VEGA","voyage":"64","port":"DAESAN","etaRaw":"10/11","remark":"","etdRaw":"","pic":"JACK","highlight":[],"id":"eta-2026-037","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-038', '{"vessel":"GOLDEN PROCYON","voyage":"2","port":"ULSAN","etaRaw":"10/13","remark":"","etdRaw":"","pic":"JAE LEE","highlight":[],"id":"eta-2026-038","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-039', '{"vessel":"KISO","voyage":"HBR 4","port":"ULSAN","etaRaw":"10/14","remark":"","etdRaw":"","pic":"JAE LEE","highlight":[],"id":"eta-2026-039","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-040', '{"vessel":"S.AJISAI","voyage":"136","port":"ULSAN","etaRaw":"10/15","remark":"","etdRaw":"","pic":"JACK","highlight":[],"id":"eta-2026-040","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-041', '{"vessel":"KISO","voyage":"TPW 3","port":"P''TAEK","etaRaw":"10/16","remark":"","etdRaw":"","pic":"JAE LEE","highlight":[],"id":"eta-2026-041","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-042', '{"vessel":"S.STRENGTH","voyage":"TPW 117","port":"ULSAN","etaRaw":"10/17","remark":"","etdRaw":"","pic":"DENNIS","highlight":[],"id":"eta-2026-042","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1),
('eta-2026-043', '{"vessel":"S.TSUBAKI","voyage":"135","port":"ULSAN","etaRaw":"10/18","remark":"","etdRaw":"","pic":"JAE LEE","highlight":[],"id":"eta-2026-043","year":2026,"status":"PRE-ARRIVAL","activities":[],"cargo":[],"crew":[],"tasks":[],"notes":"","latestReport":"","reportType":"DEP.REPORT","reportReceived":"","reportChecked":false,"sof":null}'::jsonb, 1)
on conflict (id) do nothing;
-- Invite staff in Supabase Authentication, then add their UUID in hyopu_members.
-- Never paste passwords or service keys into source control or a public message.
