// @vitest-environment node
import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import { beforeAll,beforeEach,afterAll,it,expect } from 'vitest';
let db:PGlite;
async function rpc(name:string,args:unknown[]=[]){return (await db.query<{v:any}>(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) v`,args)).rows[0].v;}
async function start(user=123){const id=crypto.randomUUID();await rpc('pilot_mini_save',['-1',user,id,0,'CREATE','sealed']);return id;}
beforeAll(async()=>{db=new PGlite();await db.exec('create role anon;create role authenticated;create role service_role bypassrls;');
 for(const f of ['20260920000000_ulsan_pilot_watcher','20260920000300_hpbot_operations','20260920000400_hpbot_telegram','20260920000500_hpbot_query_context','20260920000600_hpbot_mooring','20260920000700_pilot_registration','20260920000900_pilot_miniapp'])await db.exec(readFileSync('supabase/migrations/'+f+'.sql','utf8'));
},30000);
afterAll(async()=>{await db?.close();});
beforeEach(async()=>{await db.exec(`truncate pilot_action_logs,pilot_registration_requests,pilot_telegram_updates,pilot_telegram_chats,pilot_miniapp_limits,pilot_notifications,pilot_notification_attempts,pilot_usage;
delete from pilot_watcher_control;insert into pilot_watcher_control(id,enabled,billing_verified_at,cycle_start,cycle_end) values(true,true,now(),'2000-01-01','2100-01-01');
delete from pilot_registration_control;insert into pilot_registration_control(id,create_enabled,update_enabled) values(true,false,false);
insert into pilot_telegram_chats(chat_id) values('-1'),('-2');`);});
it('Mini App draft has no fabricated update and generates no chat message',async()=>{const id=await start();const r=(await db.query<any>('select * from pilot_registration_requests where id=$1',[id])).rows[0];expect(r.last_update_id).toBeNull();expect(r.transport).toBe('miniapp');expect((await db.query<any>('select count(*)::int n from pilot_telegram_updates')).rows[0].n).toBe(0);expect((await db.query<any>('select count(*)::int n from pilot_notifications')).rows[0].n).toBe(0);});
it('other owner/room cannot load, save or confirm',async()=>{const id=await start();expect(await rpc('pilot_mini_open',['-1',456,id])).toEqual({});expect(await rpc('pilot_mini_open',['-2',123,id])).toEqual({});await expect(rpc('pilot_mini_save',['-1',456,id,1,'CREATE','new'])).rejects.toThrow('MINI_STALE');expect(await rpc('pilot_mini_decide',['-1',456,id,1,'CONFIRM'])).toBe('STALE');});
it('revision fencing, separate admins, no silently replacing active drafts',async()=>{const id=await start();await start(456);expect(await rpc('pilot_mini_save',['-1',123,id,1,'CREATE','new'])).toBe(2);await expect(rpc('pilot_mini_save',['-1',123,id,1,'CREATE','stale'])).rejects.toThrow('MINI_STALE');await expect(start()).rejects.toThrow('MINI_EXISTING_DRAFT');expect(await rpc('pilot_mini_decide',['-1',123,id,1,'CONFIRM'])).toBe('STALE');});
it('expiration and cancellation do not cancel external applications',async()=>{const id=await start();await db.exec("update pilot_registration_requests set expires_at=now()-interval '1 second'");expect(await rpc('pilot_mini_decide',['-1',123,id,1,'CONFIRM'])).toBe('STALE');const next=await start();expect(await rpc('pilot_mini_decide',['-1',123,next,1,'CANCEL'])).toBe('CANCELLED');expect((await db.query<any>('select count(*)::int n from pilot_action_logs')).rows[0].n).toBe(0);});
it('flags remain false and prevent approval',async()=>{expect(await rpc('pilot_mini_decide',['-1',123,await start(),1,'CONFIRM'])).toBe('DISABLED');});
it('double confirmation only produces one request and one POST permit',async()=>{await db.exec('update pilot_registration_control set create_enabled=true');const id=await start();expect(await rpc('pilot_mini_decide',['-1',123,id,1,'CONFIRM'])).toBe('CONFIRMED');const at=(await db.query<any>('select confirmed_at from pilot_registration_requests')).rows[0].confirmed_at;expect(await rpc('pilot_mini_decide',['-1',123,id,1,'CONFIRM'])).toBe('CONFIRMED');expect((await db.query<any>('select confirmed_at from pilot_registration_requests')).rows[0].confirmed_at).toEqual(at);const claim=await rpc('pilot_reg_claim',[id]);expect(claim.recovery).toBe(false);expect(await rpc('pilot_reg_submitting',[id,claim.token,'prepared'])).toBe(true);expect(await rpc('pilot_reg_submitting',[id,claim.token,'prepared'])).toBe(false);});
it('cost stop blocks app reads, draft changes and confirmations',async()=>{const id=await start();await db.exec("update pilot_registration_control set create_enabled=true;update pilot_watcher_control set enabled=false,disabled_reason='EGRESS_BUDGET'");expect((await rpc('pilot_mini_open',['-1',123,id])).error).toBe('MINI_BUDGET');expect(await rpc('pilot_mini_decide',['-1',123,id,1,'CONFIRM'])).toBe('BUDGET');await expect(rpc('pilot_mini_save',['-1',123,id,1,'CREATE','new'])).rejects.toThrow('MINI_STOPPED');});
it('distributed rate limit and reservation bound apply',async()=>{for(let i=0;i<30;i++)expect((await rpc('pilot_mini_open',['-1',123])).error).toBeUndefined();expect((await rpc('pilot_mini_open',['-1',123])).error).toBe('MINI_RATE_LIMIT');expect((await rpc('pilot_mini_open',['-1',456,null,999])).error).toBe('MINI_ROOM');});
it('RLS and all API RPCs deny anon/authenticated',async()=>{for(const role of ['anon','authenticated']){await db.exec('set role '+role);for(const name of ['pilot_mini_open','pilot_mini_save','pilot_mini_decide']){const args=name==='pilot_mini_open'?['-1',123]:name==='pilot_mini_save'?['-1',123,crypto.randomUUID(),0,'CREATE','sealed']:['-1',123,crypto.randomUUID(),1,'CONFIRM'];await expect(rpc(name,args)).rejects.toThrow('permission denied');}await expect(db.query('select * from pilot_miniapp_limits')).rejects.toThrow('permission denied');await db.exec('reset role');}});
