// @vitest-environment node
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {beforeAll,beforeEach,afterAll,it,expect} from 'vitest';
let db:PGlite;
const row=(id:string|null='101',status='ACTIVE')=>({application_id:id,agent:'협운',vessel_name:'SHIP A',callsign:'CALL1',pilot_date:new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}),pilot_time:'12:00',from_location:'P/S',to_location:'OTK(S)',application_status:status==='ACTIVE'?'020':'060',completion_status:status,draft:'9.20',mooring_name:'진산',remarks:''});
async function rpc(name:string,args:unknown[]=[]){return (await db.query<any>(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) v`,args)).rows[0].v;}
beforeAll(async()=>{db=new PGlite();await db.exec('create role anon;create role authenticated;create role service_role bypassrls;');for(const f of ['20260920000000_ulsan_pilot_watcher','20260920000300_hpbot_operations','20260920000400_hpbot_telegram','20260920000500_hpbot_query_context','20260920000600_hpbot_mooring','20260920000700_pilot_registration','20260920000900_pilot_miniapp','20260920001100_pilot_copy_registration','20260920001300_pilot_pob_date_labels','20260921001500_pilot_pob_identity','20260921001600_pilot_concise_notifications','20260922002400_pilot_notification_policy','20260922002500_pilot_event_titles'])await db.exec(readFileSync('supabase/migrations/'+f+'.sql','utf8'));},30000);
afterAll(async()=>await db?.close());
beforeEach(async()=>await db.exec(`truncate pilot_action_logs,pilot_registration_requests,pilot_copy_sources,pilot_copy_jobs,pilot_telegram_chats,pilot_miniapp_limits,pilot_notifications,pilot_notification_attempts,pilot_usage,hpbot_pilot_current;
delete from pilot_watcher_control;insert into pilot_watcher_control(id,enabled,billing_verified_at,cycle_start,cycle_end) values(true,true,now(),'2000-01-01','2100-01-01');
update pilot_registration_control set create_enabled=false,update_enabled=false,copy_enabled=false,writer_id=null,writer_until=null;insert into pilot_telegram_chats(chat_id) values('-1');`));
it('indexes safe completed metadata without inventing an application ID',async()=>{await rpc('pilot_copy_index',[[row(null,'COMPLETED')]]);const list=await rpc('pilot_copy_list');expect(list.total).toBe(1);expect(list.rows[0]).toMatchObject({application_id:null,complete:false,available:false});expect(await rpc('pilot_copy_claim')).toEqual([]);});
it('only new or business changed active rows enqueue, not public or observation changes',async()=>{await db.query('insert into hpbot_pilot_current(application_id,data,first_seen_at,last_seen_at,updated_at) values($1,$2,now(),now(),now())',['101',row()]);const [job]=await rpc('pilot_copy_claim');expect(job.application_id).toBe('101');expect(await rpc('pilot_copy_store',[job.id,job.fingerprint,'a'.repeat(64),'sealed',new Date().toISOString(),job.token])).toBe(true);await db.query('update hpbot_pilot_current set data=$1,last_seen_at=now()',[{...row(),forecast_status:'PROCESSING',last_seen_at:new Date().toISOString()}]);expect(await rpc('pilot_copy_claim')).toEqual([]);await db.query('update hpbot_pilot_current set data=$1',[{...row(),pilot_time:'13:00'}]);expect(await rpc('pilot_copy_claim')).toHaveLength(1);});
it('capture lease handles two jobs and rejects stale capture',async()=>{await rpc('pilot_copy_index',[[row('101'),row('102'),row('103')]]);const jobs=await rpc('pilot_copy_claim');expect(jobs).toHaveLength(2);expect(await rpc('pilot_copy_claim')).toHaveLength(1);await rpc('pilot_copy_index',[[{...row('101'),pilot_time:'14:00'}]]);const j=jobs.find((x:any)=>x.application_id==='101');if(j)expect(await rpc('pilot_copy_store',[j.id,j.fingerprint,'a'.repeat(64),'sealed',new Date().toISOString(),j.token])).toBe(false);});
it('copy draft is CREATE, owner bound, 30 minute lifetime and two flags gate it',async()=>{await rpc('pilot_copy_index',[[row()]]);const source=(await rpc('pilot_copy_list')).rows[0];const id=crypto.randomUUID();expect(await rpc('pilot_mini_save',['-1',123,id,0,'CREATE','sealed',null,null,source.id,'a'.repeat(64)])).toBe(1);const r=(await db.query<any>('select action,extract(epoch from expires_at-created_at)::int ttl from pilot_registration_requests')).rows[0];expect(r).toEqual({action:'CREATE',ttl:1800});await db.exec('update pilot_registration_control set create_enabled=true');expect(await rpc('pilot_mini_decide',['-1',123,id,1,'CONFIRM'])).toBe('DISABLED');expect(await rpc('pilot_mini_decide',['-1',456,id,1,'CONFIRM'])).toBe('STALE');await db.exec('update pilot_registration_control set copy_enabled=true');expect(await rpc('pilot_mini_decide',['-1',123,id,1,'CONFIRM'])).toBe('CONFIRMED');const claim=await rpc('pilot_reg_claim',[id]);expect(await rpc('pilot_reg_submitting',[id,claim.token,'prepared'])).toBe(true);expect(await rpc('pilot_reg_submitting',[id,claim.token,'prepared'])).toBe(false);});
it('cannot turn copy into update or remove its source',async()=>{await rpc('pilot_copy_index',[[row()]]);const source=(await rpc('pilot_copy_list')).rows[0];await expect(rpc('pilot_mini_save',['-1',123,crypto.randomUUID(),0,'UPDATE','sealed',null,'101',source.id,'a'.repeat(64)])).rejects.toThrow('COPY_SOURCE_INVALID');const id=crypto.randomUUID();await rpc('pilot_mini_save',['-1',123,id,0,'CREATE','sealed',null,null,source.id,'a'.repeat(64)]);await expect(rpc('pilot_mini_save',['-1',123,id,1,'CREATE','new'])).rejects.toThrow('COPY_MODE_IMMUTABLE');});
it('excludes cancelled and out of range completed rows, retains old unfinished and future jobs',async()=>{await rpc('pilot_copy_index',[[row('101','CANCELLED'),{...row('102','COMPLETED'),pilot_date:'2000-01-01'},{...row('103'),pilot_date:'2000-01-01'},{...row('104'),pilot_date:'2099-01-01'}]]);const l=await rpc('pilot_copy_list');expect(l.total).toBe(2);expect(l.rows.map((r:any)=>r.application_id)).toEqual(['103','104']);});
it('cost stop prevents captures, RLS blocks browser source access',async()=>{await rpc('pilot_copy_index',[[row()]]);await db.exec('update pilot_watcher_control set enabled=false');expect(await rpc('pilot_copy_claim')).toEqual([]);for(const role of ['anon','authenticated']){await db.exec('set role '+role);await expect(rpc('pilot_copy_list')).rejects.toThrow('permission denied');await expect(db.query('select * from pilot_copy_sources')).rejects.toThrow('permission denied');await db.exec('reset role');}});
it('verified copy inserts one new row, receipt rank and business-only encrypted audit without altering source',async()=>{
 await db.query('insert into hpbot_pilot_current(application_id,data,first_seen_at,last_seen_at,updated_at) values($1,$2,now(),now(),now())',['101',row()]);
 const source=(await rpc('pilot_copy_list')).rows[0],id=crypto.randomUUID();
 await rpc('pilot_mini_save',['-1',123,id,0,'CREATE','draft-containing-fresh-tokens',null,null,source.id,'a'.repeat(64),'sealed-business-only']);
 await db.exec('update pilot_registration_control set create_enabled=true,copy_enabled=true');
 await rpc('pilot_mini_decide',['-1',123,id,1,'CONFIRM']);const claim=await rpc('pilot_reg_claim',[id]);
 expect(await rpc('pilot_reg_submitting',[id,claim.token,'prepared'])).toBe(true);
 expect(await rpc('pilot_reg_finish',[id,claim.token,'SUCCESS',null,{...row('102'),pilot_time:'13:00'},'복사등록 완료'])).toBe(true);
 expect((await db.query<any>('select pilot_time from hpbot_pilot_current where application_id=\'101\'')).rows[0].pilot_time).toBe('12:00');
 expect((await db.query<any>('select message from pilot_notifications')).rows[0].message).toContain('현재 순번: 2번');
 expect((await db.query<any>('select copy_audit_sealed from pilot_action_logs')).rows[0].copy_audit_sealed).toBe('sealed-business-only');
 expect(await rpc('pilot_reg_finish',[id,claim.token,'SUCCESS',null,row('102'),'again'])).toBe(false);
 expect((await db.query<any>('select count(*)::int n from pilot_notifications')).rows[0].n).toBe(1);
});
