// @vitest-environment node
import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import { beforeAll,beforeEach,afterAll,describe,it,expect } from 'vitest';
let db:PGlite;let update=0;
async function rpc(name:string,args:unknown[]=[]){return (await db.query<{v:any}>(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) v`,args)).rows[0].v;}
const j=JSON.stringify;
const row=(id='900',time='12:00')=>({application_id:id,vessel_name:'TEST VESSEL',callsign:'TEST1',pilot_date:'2099-01-01',pilot_time:time,from_location:'P/S',to_location:'OTK(S)',application_status:'010',completion_status:'ACTIVE',agent:'협운',remarks:'',mooring_name:'진산'});
async function accepted(user=123,chat='-1'){const id=++update;await db.exec('truncate pilot_telegram_updates');expect(await rpc('hpbot_accept_update',[id,chat,user,'registration'])).toBe(true);return id;}
async function draft(user=123,action='CREATE'){const u=await accepted(user);const id=crypto.randomUUID();await rpc('pilot_reg_start',[u,id,action,'encrypted']);return {id,u};}
async function confirmed(user=123){const r=await draft(user);const u=await accepted(user);expect(await rpc('pilot_reg_decide',[u,r.id,1,'CONFIRM'])).toBe('CONFIRMED');return r.id;}
beforeAll(async()=>{db=new PGlite();await db.exec('create role anon;create role authenticated;create role service_role bypassrls;');
 for(const file of ['20260920000000_ulsan_pilot_watcher','20260920000300_hpbot_operations','20260920000400_hpbot_telegram','20260920000500_hpbot_query_context','20260920000600_hpbot_mooring','20260920000700_pilot_registration'])await db.exec(readFileSync('supabase/migrations/'+file+'.sql','utf8'));
 for(const f of ['20260920001300_pilot_pob_date_labels','20260921001500_pilot_pob_identity','20260921001600_pilot_concise_notifications','20260922002400_pilot_notification_policy','20260922002500_pilot_event_titles'])await db.exec(readFileSync('supabase/migrations/'+f+'.sql','utf8'));
},30000);
afterAll(async()=>{await db?.close();});
beforeEach(async()=>{await db.exec(`truncate pilot_action_logs,pilot_registration_requests,pilot_telegram_updates,pilot_telegram_chats,hpbot_pilot_current,hpbot_pilot_history,hpbot_source_snapshots,pilot_monitor_logs,pilot_notifications,pilot_notification_attempts,pilot_weather_events,pilot_snapshots,pilot_runs,pilot_usage;
delete from pilot_watcher_control;insert into pilot_watcher_control(id,enabled,billing_verified_at,cycle_start,cycle_end) values(true,true,now(),'2000-01-01','2100-01-01');
delete from hpbot_control;insert into hpbot_control(id,alerts_enabled,bootstrap_done) values(true,true,true);
delete from pilot_weather_state;insert into pilot_weather_state(id) values(true);
delete from pilot_registration_control;insert into pilot_registration_control(id,create_enabled,update_enabled) values(true,true,true);
insert into pilot_telegram_chats(chat_id) values('-1'),('-2');`);update=0;});
describe('registration DB authority and fencing',()=>{
 it('migration defaults both writes disabled',async()=>{await db.exec('delete from pilot_registration_control;insert into pilot_registration_control(id) values(true)');const r=await draft();const u=await accepted();expect(await rpc('pilot_reg_decide',[u,r.id,1,'CONFIRM'])).toBe('DISABLED');});
 it('owner and revision checks; independently active admin drafts',async()=>{const a=await draft(123),b=await draft(456);let u=await accepted(456);expect(await rpc('pilot_reg_get',[u,a.id])).toBeNull();u=await accepted();expect(await rpc('pilot_reg_save',[u,a.id,1,'encrypted2'])).toBe(2);u=await accepted();expect(await rpc('pilot_reg_decide',[u,a.id,1,'CONFIRM'])).toBe('STALE');expect((await db.query<any>('select count(*)::int n from pilot_registration_requests where status=\'DRAFT\'')).rows[0].n).toBe(2);expect(b.id).not.toBe(a.id);});
 it('20 minute inactivity expiry forbids confirmation; draft cancellation never touches current',async()=>{const r=await draft();await db.exec("update pilot_registration_requests set expires_at=now()-interval '1 second'");expect(await rpc('pilot_reg_decide',[await accepted(),r.id,1,'CONFIRM'])).toBe('STALE');const n=await draft();expect(await rpc('pilot_reg_decide',[await accepted(),n.id,1,'CANCEL'])).toBe('CANCELLED');expect((await db.query<any>('select count(*)::int n from hpbot_pilot_current')).rows[0].n).toBe(0);});
 it('input binding requires latest delivered question, correct owner and group',async()=>{const r=await draft();await rpc('pilot_reg_reply',[r.u,r.id,1,'question',j({force_reply:true}),10]);await db.exec("update pilot_notifications set status='SENT',telegram_message_id=11");expect(await rpc('pilot_reg_is_reply',['-1',123,11])).toBe(true);expect(await rpc('pilot_reg_is_reply',['-1',456,11])).toBe(false);expect(await rpc('pilot_reg_is_reply',['-2',123,11])).toBe(false);await rpc('pilot_reg_save',[await accepted(),r.id,1,'new']);expect(await rpc('pilot_reg_is_reply',['-1',123,11])).toBe(false);});
 it('atomic submit CAS only once and account lease serializes multiple admins',async()=>{const a=await confirmed(),b=await confirmed(456);const claim=await rpc('pilot_reg_claim',[a]);expect(claim.token).toBeTruthy();expect(await rpc('pilot_reg_claim',[a])).toBeNull();expect(await rpc('pilot_reg_claim',[b])).toBeNull();expect(await rpc('pilot_reg_submitting',[a,claim.token,'prepared'])).toBe(true);expect(await rpc('pilot_reg_submitting',[a,claim.token,'prepared'])).toBe(false);expect((await rpc('hpbot_begin')).skip).toBe('REGISTRATION_BUSY');});
 it('watcher active lease prevents registration, registration changes watcher version',async()=>{const id=await confirmed();await db.exec("update pilot_watcher_control set lease_until=now()+interval '50 seconds'");expect(await rpc('pilot_reg_claim',[id])).toBeNull();await db.exec('update pilot_watcher_control set lease_until=null');expect((await rpc('pilot_reg_claim',[id])).token).toBeTruthy();expect((await db.query<any>('select version from pilot_watcher_control')).rows[0].version).toBe(1);});
 it('post-POST failure cannot be FAILED and UNKNOWN only receives recovery permit',async()=>{const id=await confirmed(),c=await rpc('pilot_reg_claim',[id]);await rpc('pilot_reg_submitting',[id,c.token,'prepared']);await expect(rpc('pilot_reg_finish',[id,c.token,'FAILED','REG_TEST'])).rejects.toThrow('REG_UNCERTAIN_STATUS');await rpc('pilot_reg_finish',[id,c.token,'UNKNOWN','REG_TEST']);const r=await rpc('pilot_reg_claim',[id]);expect(r.recovery).toBe(true);expect(await rpc('pilot_reg_submitting',[id,r.token,'prepared'])).toBe(false);});
 it('interrupted SUBMITTING recovery never gets a fresh POST permit',async()=>{const id=await confirmed(),c=await rpc('pilot_reg_claim',[id]);await rpc('pilot_reg_submitting',[id,c.token,'prepared']);await db.exec("update pilot_registration_control set writer_until=now()-interval '1 second';update pilot_registration_requests set worker_until=now()-interval '1 second'");const r=await rpc('pilot_reg_claim',[id]);expect(r.recovery).toBe(true);expect(await rpc('pilot_reg_submitting',[id,r.token,'prepared'])).toBe(false);expect(await rpc('pilot_reg_finish',[id,c.token,'UNKNOWN','OLD_WORKER'])).toBe(false);});
 it('verified single upsert preserves unrelated jobs and current rank, avoids watcher duplicate NEW',async()=>{await db.query<any>('insert into hpbot_pilot_current(application_id,data,first_seen_at,last_seen_at,updated_at) values($1,$2,now(),now(),now())',['500',j(row('500','14:00'))]);
   const id=await confirmed(),c=await rpc('pilot_reg_claim',[id]);await rpc('pilot_reg_submitting',[id,c.token,'prepared']);expect(await rpc('pilot_reg_finish',[id,c.token,'SUCCESS',null,j(row()),'success'])).toBe(true);
   const q=await db.query<any>('select application_id,sequence_no from hpbot_pilot_queue order by sequence_no');expect(q.rows.map((r:any)=>r.application_id)).toEqual(['900','500']);
   const old=(await db.query<any>('select data from hpbot_pilot_current')).rows.map((r:any)=>r.data);const plan=await rpc('hpbot_plan',[j(old),j([row(),row('500','14:00')]),'[]','[]',false,false,new Date().toISOString()]);expect(plan.changes).toEqual([]);
   expect((await db.query<any>('select count(*)::int n from pilot_action_logs')).rows[0].n).toBe(1);expect((await db.query<any>('select count(*)::int n from pilot_notifications')).rows[0].n).toBe(1);
   expect(await rpc('pilot_reg_finish',[id,c.token,'SUCCESS',null,j(row()),'duplicate'])).toBe(false);
 });
 it('cost stop blocks confirmation and claim, never reenables budget',async()=>{const r=await draft();await db.exec("update pilot_watcher_control set enabled=false,disabled_reason='EGRESS_BUDGET'");expect(await rpc('pilot_reg_decide',[await accepted().catch(()=>update),r.id,1,'CONFIRM'])).not.toBe('CONFIRMED');expect(await rpc('pilot_reg_claim',[r.id])).toBeNull();expect((await db.query<any>('select enabled from pilot_watcher_control')).rows[0].enabled).toBe(false);});
 it('RLS and service-role-only RPCs',async()=>{for(const role of ['anon','authenticated']){await db.exec('set role '+role);await expect(rpc('pilot_reg_context')).rejects.toThrow('permission denied');await expect(db.query<any>('select * from pilot_registration_requests')).rejects.toThrow('permission denied');await db.exec('reset role');}});
});
