// @vitest-environment happy-dom
import {describe,it,expect,vi,afterEach} from 'vitest';
// @ts-ignore isolated static frontend
import {mountMiniApp} from '../pilot-miniapp/app.js';
const tick=()=>new Promise(r=>setTimeout(r,0));
const fields=[{key:'vessel',label:'선박',kind:'lookup',value:'GINGA / CALL1'},{key:'dt_ship',label:'도선 날짜',kind:'date',value:'2026-09-22'},{key:'time',label:'도선 시간',kind:'time',value:'06:15'},...['from','to','mooring','shipcompany','billing'].map(key=>({key,label:key,kind:'lookup',value:'selected'})),{key:'num_draft',label:'최대흘수',kind:'text',value:'9.20'},{key:'fg_side',label:'접안현',kind:'select',options:[{index:0,label:'S'},{index:1,label:'P'}],selected:0},{key:'cd_emp_partner',label:'담당자',kind:'text',saved:true,value:''},{key:'nm_text',label:'비고',kind:'textarea',value:''}];
const view={id:'request',revision:1,status:'DRAFT',step:'edit',action:'CREATE',summary:'GINGA / CALL1\n강취: 진산',formFields:fields,enabled:true};
const click=(root:HTMLElement,text:string)=>{const b=Array.from(root.querySelectorAll('button')).find(b=>b.textContent===text)!;expect(b).toBeTruthy();b.click();};
async function setup(api:any){const root=document.createElement('main');document.body.append(root);mountMiniApp(root,api);await tick();return root;}
afterEach(()=>document.body.replaceChildren());
describe('single-page Mini App',()=>{
 it('shows the official advisory warning before both confirmation levels without submitting automatically',async()=>{
  const api=vi.fn(async({op}:any)=>op==='confirm'?{status:'CONFIRMED'}:{...view,step:op==='save'?'review':'edit',eligibilityPolicy:'official-ui-advisory-v1',eligibilityWarnings:['청구처 연체 여부를 보조검사로 확인하지 못했습니다.']}),root=await setup(api);
  expect(root.querySelector('[data-eligibility-warning]')).toBeNull();click(root,'전체 내용 검토');await tick();
  const warning=root.querySelector('[data-eligibility-warning]')!;expect(warning.textContent).toContain('최종 접수는 도선사회 서버가 판정합니다.');expect(warning.textContent).toContain('청구처 연체 여부를 보조검사로 확인하지 못했습니다.');expect(api.mock.calls.some(([arg])=>arg.op==='confirm')).toBe(false);
  const submit=Array.from(root.querySelectorAll('button')).find(b=>b.textContent==='최종 도선신청')!;expect(warning.compareDocumentPosition(submit)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
  click(root,'최종 도선신청');expect(root.querySelector('[data-eligibility-warning]')?.textContent).toContain('연체 여부는 확인되지 않을 수');expect(api).toHaveBeenCalledTimes(2);
  click(root,'✅ 등록확정');await tick();expect(api.mock.calls.filter(([arg])=>arg.op==='confirm')).toHaveLength(1);expect(api.mock.calls.at(-1)?.[0]).toMatchObject({op:'confirm',eligibilityPolicy:'official-ui-advisory-v1'});
 });
 it('does not show the advisory policy for strict mode and displays dry-run warnings as a notice only',async()=>{
  const api=vi.fn(async({op}:any)=>({...view,step:'review',...(op==='dry'?{notice:'보조검사 경고: 시간 검사 응답 없음. 실제 신청은 전송하지 않았습니다.'}:{})})),root=await setup(api);
  click(root,'전체 내용 검토');await tick();expect(root.querySelector('[data-eligibility-warning]')).toBeNull();click(root,'🧪 전송 없이 검사');await tick();
  expect(root.textContent).toContain('보조검사 경고: 시간 검사 응답 없음. 실제 신청은 전송하지 않았습니다.');expect(api.mock.calls.map(([arg])=>arg.op)).toEqual(['load','save','dry']);expect(root.textContent).not.toContain('✅ 등록확정');
 });
 it('renders advisory details as plain text without source markup',async()=>{
  const root=await setup(vi.fn(async()=>({...view,step:'review',eligibilityPolicy:'official-ui-advisory-v1',eligibilityWarnings:['<img src=x onerror=alert(1)>']})));
  click(root,'전체 내용 검토');await tick();expect(root.querySelector('[data-eligibility-warning]')?.textContent).toContain('<img');expect(root.querySelector('img,script')).toBeNull();
 });
 it('keeps an existing 23-character remark and allows editing without an invented 20-character cap',async()=>{
  const remark='R'.repeat(23),fs=fields.map(f=>f.key==='nm_text'?{...f,value:remark,maxLength:1200}:f);
  const api=vi.fn(async()=>({...view,action:'UPDATE',formFields:fs,originalFields:fs})),root=await setup(api),input=root.querySelector<HTMLTextAreaElement>('#field-nm_text')!;
  expect(input.value).toBe(remark);expect(input.maxLength).toBe(1200);input.value=remark+'!';input.dispatchEvent(new Event('input'));
  click(root,'초안 저장');await tick();expect(api.mock.calls[1][0].values).toEqual({nm_text:remark+'!'});
 });
 it('uses a real server-provided remark maxlength when the source declares one',async()=>{
  const root=await setup(vi.fn(async()=>({...view,formFields:fields.map(f=>f.key==='nm_text'?{...f,maxLength:40}:f)})));
  expect(root.querySelector<HTMLTextAreaElement>('#field-nm_text')!.maxLength).toBe(40);
 });
 it('accepts 0615 directly and saves canonical 06:15 without a segmented clock input',async()=>{const api=vi.fn(async()=>view),root=await setup(api),input=root.querySelector<HTMLInputElement>('#field-time')!;expect(input.type).toBe('text');expect(input.inputMode).toBe('numeric');for(const [raw,formatted] of [['0615','06:15'],['2359','23:59'],['0000','00:00'],['06:15','06:15'],['2460','2460'],['615','615']]){input.value=raw;input.dispatchEvent(new Event('input'));expect(input.value).toBe(formatted);}input.value='0615';input.dispatchEvent(new Event('input'));click(root,'초안 저장');await tick();expect(api.mock.calls[1][0].values).toEqual({time:'06:15'});});
 it('copy shows full contact values and original comparison but no editable contact inputs',async()=>{const contacts=[{key:'cd_emp_partner',label:'담당자',kind:'text',value:'TEST PERSON',readonly:true},{key:'no_hpemp_partner',label:'연락처',kind:'text',value:'010-1234-5678',readonly:true},{key:'e_mail',label:'청구 이메일',kind:'text',value:'test@example.test',readonly:true}],fs=[...fields.filter(f=>!contacts.some(c=>c.key===f.key)),...contacts],root=await setup(vi.fn(async()=>({...view,mode:'COPY',formFields:fs,originalFields:fs})));for(const c of contacts){expect(root.querySelector(`[data-field="${c.key}"]`)?.textContent).toContain(c.value);expect(root.querySelector(`#field-${c.key}`)).toBeNull();}expect(root.textContent).not.toContain('••••');});
 it('copy locks every business field except date time and route',async()=>{const fs=fields.map(f=>({...f,readonly:!['dt_ship','time','from','to'].includes(f.key)}));const root=await setup(vi.fn(async()=>({...view,mode:'COPY',formFields:fs,originalFields:fs,copySource:{date:'2026-09-20',observedAt:'2026-09-20T00:00:00Z',archived:true}})));expect(root.querySelector('#field-num_draft')).toBeNull();expect(root.querySelector('#field-fg_side')).toBeNull();expect(root.querySelector('#field-time')).not.toBeNull();expect(root.textContent).toContain('보관된 원본 사용');expect(root.textContent).toContain('원본 신청은 수정하지 않습니다');});
 it('formats newly typed mobile/landline without replacing existing contact on load',async()=>{const api=vi.fn(async()=>({...view,action:'UPDATE',formFields:[...fields,{key:'no_hpemp_partner',label:'연락처',kind:'text',value:'0529999999'}]})),root=await setup(api);const input=root.querySelector<HTMLInputElement>('#field-no_hpemp_partner')!;expect(input.value).toBe('0529999999');for(const [raw,formatted] of [['01012345678','010-1234-5678'],['0521234567','052-123-4567']]){input.value=raw;input.dispatchEvent(new Event('input'));expect(input.value).toBe(formatted);}expect(api).toHaveBeenCalledTimes(1);});
 it('copy list displays but disables incomplete historical sources',async()=>{const api=vi.fn(async({op}:any)=>op==='copyList'?{page:0,total:1,rows:[{id:'old',available:false,metadata:{vessel_name:'SHIP A',callsign:'CALL1',pilot_date:'2026-09-19',pilot_time:'12:00',from_location:'P/S',to_location:'OTK(S)',completion_status:'COMPLETED'}}]}:{status:'EMPTY'}),root=await setup(api);click(root,'📋 기존 도선 복사');await tick();expect(root.textContent).toContain('최근 완료·청구');expect(root.textContent).toContain('원본 상세 부족 — 복사 불가');expect(Array.from(root.querySelectorAll('button')).find(b=>b.textContent?.includes('SHIP A'))!.disabled).toBe(true);});
 it('prefills update fields including contacts and shows before/after without losing untouched values',async()=>{const updateFields=[...fields.filter(f=>f.key!=='cd_emp_partner'),{key:'cd_emp_partner',label:'담당자',kind:'text',value:'TEST CONTACT'}];const api=vi.fn(async()=>({...view,action:'UPDATE',formFields:updateFields,originalFields:updateFields})),root=await setup(api);expect(root.querySelector<HTMLInputElement>('#field-cd_emp_partner')!.value).toBe('TEST CONTACT');expect(root.querySelector<HTMLInputElement>('#field-time')!.value).toBe('06:15');const input=root.querySelector<HTMLInputElement>('#field-time')!;input.value='08:30';input.dispatchEvent(new Event('input'));expect(root.querySelector('[data-field="time"]')!.textContent).toContain('06:15 → 08:30');expect(root.querySelector('[data-field="time"]')!.classList.contains('is-changed')).toBe(true);click(root,'초안 저장');await tick();expect(api.mock.calls[1][0].values).toEqual({time:'08:30'});});
 it('renders every field at once with no next-step buttons',async()=>{const api=vi.fn(async()=>view),root=await setup(api);for(const f of fields)expect(root.querySelector(`[data-field="${f.key}"]`)).not.toBeNull();expect(root.querySelector('progress')).toBeNull();expect(Array.from(root.querySelectorAll('button')).some(b=>b.textContent==='다음')).toBe(false);expect(api).toHaveBeenCalledTimes(1);});
 it('saves all edits in one request and separately confirms',async()=>{const api=vi.fn(async({op}:any)=>op==='confirm'?{status:'CONFIRMED'}:{...view,step:op==='save'?'review':'edit',revision:op==='save'?2:1}),root=await setup(api);const input=root.querySelector<HTMLInputElement>('#field-time')!;input.value='08:30';input.dispatchEvent(new Event('input'));const select=root.querySelector<HTMLSelectElement>('#field-fg_side')!;select.value='1';select.dispatchEvent(new Event('change'));expect(api).toHaveBeenCalledTimes(1);click(root,'전체 내용 검토');await tick();expect(api.mock.calls[1][0]).toMatchObject({op:'save',values:{time:'08:30',fg_side:1},review:true});click(root,'최종 도선신청');expect(api).toHaveBeenCalledTimes(2);click(root,'✅ 등록확정');await tick();expect(api.mock.calls[2][0].op).toBe('confirm');});
 it('keeps unsaved values across source searches and errors',async()=>{const api=vi.fn(async({op}:any)=>{if(op==='save')throw Error('NETWORK');return {...view,step:op==='search'?'from':'edit',choices:op==='search'?[{index:0,label:'OTK(S)'}]:[]};}),root=await setup(api);const input=root.querySelector<HTMLInputElement>('#field-time')!;input.value='09:45';input.dispatchEvent(new Event('input'));const search=root.querySelector<HTMLInputElement>('#field-from')!;search.value='OTK';search.dispatchEvent(new Event('input'));root.querySelector<HTMLButtonElement>('[data-field="from"] button')!.click();await tick();expect(root.querySelector<HTMLInputElement>('#field-time')!.value).toBe('09:45');expect(api.mock.calls[1][0]).toMatchObject({op:'search',field:'from',text:'OTK'});click(root,'초안 저장');await tick();expect(root.querySelector<HTMLInputElement>('#field-time')!.value).toBe('09:45');expect(root.textContent).toContain('NETWORK');});
 it('editing after review invalidates confirmation',async()=>{const api=vi.fn(async()=>({...view,step:'review'})),root=await setup(api);click(root,'전체 내용 검토');await tick();click(root,'최종 도선신청');expect(root.textContent).toContain('✅ 등록확정');const input=root.querySelector<HTMLInputElement>('#field-num_draft')!;input.value='10.00';input.dispatchEvent(new Event('input'));expect(root.querySelector('[data-review]')).toBeNull();expect(api).toHaveBeenCalledTimes(2);});
 it('disabled writes still permit dry check',async()=>{const api=vi.fn(async()=>({...view,enabled:false,step:'review'})),root=await setup(api);click(root,'전체 내용 검토');await tick();expect(Array.from(root.querySelectorAll('button')).find(b=>b.textContent==='최종 도선신청')!.disabled).toBe(true);expect(Array.from(root.querySelectorAll('button')).find(b=>b.textContent==='🧪 전송 없이 검사')!.disabled).toBe(false);});
 it('renders source strings as text and cancels only after confirmation',async()=>{const api=vi.fn(async()=>({...view,formFields:[{...fields[0],value:'<img src=x onerror=alert(1)>'}]})),root=await setup(api);expect(root.querySelector('img,script')).toBeNull();expect(root.textContent).toContain('<img');click(root,'초안 취소');expect(api).toHaveBeenCalledTimes(1);click(root,'초안 취소 확인');await tick();expect(api.mock.calls[1][0].op).toBe('cancel');});
});
